# config.yml
device: "cuda"  # Options: "cuda" or "cpu"
batch_size: 6
learning_rate: 0.001
epochs: 2

validation_split: 0.1
test_split: 0.1
random_seed: 42
num_classes: 37
S: 7
B: 2

pretrain_epochs: 2
pretrain_batch_size: 32
pretrain_learning_rate: 0.001